#:schema node_modules/wrangler/config-schema.json
name = "flux-kontext-template"
compatibility_date = "2024-06-21"
pages_build_output_dir = ".vercel/output/static"

[env.production]
compatibility_date = "2024-06-21"

[env.preview]
compatibility_date = "2024-06-21"